app/__init__.py
from flask import Flask

from app.errors.routes import error_404, error_403, error_401, error_500


def create_app():
    app = Flask(__name__)

    # Retrieve configuration information
    app.config.from_object('app.config.Config')

    app.config['MYSQL_HOST'] = 'localhost'
    app.config['MYSQL_USER'] = 'root'
    app.config['MYSQL_PASSWORD'] = 'mriganka123'
    app.config['MYSQL_DB'] = 'flask'

    # Initialization of blueprints
    from app.main import main_bp

    # Error handlers
    app.register_error_handler(404, error_404)
    app.register_error_handler(403, error_403)
    app.register_error_handler(401, error_401)
    app.register_error_handler(500, error_500)

    app.register_blueprint(main_bp)
    return app


if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint("main", __name__)

import app.main.routes

app/main/routes.py
from base64 import b64encode
# from crypt import methods
from io import BytesIO
from json.tool import main

import cv2
import numpy as np
from PIL import Image
from flask import render_template, Response, flash, request, redirect, url_for, session
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from werkzeug.exceptions import abort
from wtforms import FileField, SubmitField
from app.main import main_bp
from app.main.camera import Camera

from source.test_new_images import detect_mask_in_image
from source.video_detector import detect_mask_in_frame

import mysql.connector
import re

mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="mriganka123",
    database="flask"
)

# mycursor = mydb.cursor()

# mycursor.execute("SHOW DATABASES")

# for x in mycursor:
#     print(x)


@main_bp.route("/")
def home_page():
    return render_template("home_page.html")


def gen(camera):
    while True:
        frame = camera.get_frame()
        frame_processed, mask_or_not = detect_mask_in_frame(frame)
        # print(mask_or_not)
        frame_processed = cv2.imencode('.jpg', frame_processed)[1].tobytes()
        yield (b'--frame\r\n' b'Content-Type: image/jpeg\r\n\r\n' + frame_processed + b'\r\n')


@main_bp.route('/video_feed')
def video_feed():
    return Response(gen(Camera()), mimetype='multipart/x-mixed-replace; boundary=frame')


def allowed_file(filename):
    ext = filename.split(".")[-1]
    is_good = ext in ["jpg", "jpeg", "png"]
    return is_good


@main_bp.route("/image-mask-detector", methods=["GET", "POST"])
def image_mask_detection():
    return render_template("image_detector.html",
                           form=PhotoMaskForm())


@main_bp.route("/image-processing", methods=["POST"])
def image_processing():
    form = PhotoMaskForm()

    if not form.validate_on_submit():
        flash("An error occurred", "danger")
        abort(Response("Error", 400))

    pil_image = Image.open(form.image.data)
    image = cv2.cvtColor(np.array(pil_image), cv2.COLOR_RGB2BGR)
    array_image = detect_mask_in_image(image)
    rgb_image = cv2.cvtColor(array_image, cv2.COLOR_BGR2RGB)
    image_detected = Image.fromarray(rgb_image, 'RGB')

    with BytesIO() as img_io:
        image_detected.save(img_io, 'PNG')
        img_io.seek(0)
        base64img = "data:image/png;base64," + \
            b64encode(img_io.getvalue()).decode('ascii')
        return base64img


@main_bp.route("/login", methods=['GET', "POST"])
def login():
    # Output message if something goes wrong...
    msg = ''
    # Check if "username" and "password" POST requests exist (user submitted form)
    if request.method == 'POST' and 'username' in request.form and 'username' in request.form and 'password' in request.form:
        # Create variables for easy access
        username = request.form['username']
        code = request.form['code']
        password = request.form['password']
        # Check if account exists using MySQL
        cursor = mydb.cursor()
        cursor.execute(
            'SELECT * FROM employee WHERE username = %s AND code = %s AND password = %s', (username, code, password,))
        # Fetch one record and return result
        account = cursor.fetchone()
        # print(account)
        # If account exists in accounts table in out database
        if account:
            # Create session data, we can access this data in other routes
            session['loggedin'] = True
            session['id'] = account[5]
            session['username'] = account[2]
            # Redirect to home page
            # return 'Logged in successfully!'
            cursor.execute(
                "INSERT INTO `attendence`(`code`, `date`, `isPresent`) VALUES(%s, current_timestamp(), 'P')",
                (code,)
            )
            mydb.commit()
            flash(account[1] + " logged in and attendence given successfully!")
            return redirect(url_for('main.home_page'))
        else:
            # Account doesnt exist or username/password incorrect
            msg = 'Incorrect username/password!'
    # Show the login form with message (if any)
    return render_template("login.html", msg=msg)


@main_bp.route("/register", methods=['GET', "POST"])
def register():
    msg = ''
    # Check if "username", "password" and "email" POST requests exist (user submitted form)
    if request.method == 'POST' and 'name' in request.form and 'username' in request.form and 'code' in request.form and 'password' in request.form and 'email' in request.form:
        # Create variables for easy access
        name = request.form['name']
        username = request.form['username']
        code = request.form['code']
        password = request.form['password']
        email = request.form['email']
        # Check if account exists using MySQL
        cursor = mydb.cursor()
        cursor.execute(
            'SELECT * FROM employee WHERE code = %s', (code,))
        account = cursor.fetchone()
        # If account exists show error and validation checks
        if account:
            msg = 'Account already exists!'
        elif not re.match(r'[^@]+@[^@]+\.[^@]+', email):
            msg = 'Invalid email address!'
        elif not re.match(r'[A-Za-z0-9]+', username):
            msg = 'Username must contain only characters and numbers!'
        elif not username or not password or not email:
            msg = 'Please fill out the form!'
        else:
            # Account doesnt exists and the form data is valid, now insert new account into accounts table
            cursor.execute(
                'INSERT INTO employee VALUES (NULL, %s, %s, %s, %s, %s)', (name, username, password, email, code,))
            mydb.commit()
            msg = name + ' successfully registered!'
    elif request.method == 'POST':
        # Form is empty... (no POST data)
        msg = 'Please fill out the form!'
    # Show registration form with message (if any)
    return render_template('register.html', msg=msg)


@main_bp.route('/logout')
def logout():
    session.pop('loggedin', None)
    session.pop('id', None)
    session.pop('username', None)
    return redirect("/")


# form
class PhotoMaskForm(FlaskForm):
    image = FileField('Choose image:',
                      validators=[
                          FileAllowed(['jpg', 'jpeg', 'png'], 'The allowed extensions are: .jpg, .jpeg and .png')])

    submit = SubmitField('Detect mask')

app/templates/error.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="container text-center">
        <h1>Error {{error}}</h1>
        <p class="lead">An errror occurred, please try again</p>
        <div class="row mt-5 d-flex justify-content-center">
            <a role="button" class="btn btn-lg btn-outline-info" href="/">Home page</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home_page.html
{% extends "template.html" %}

{% block content %}

<div class="container">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-dark alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
</div>

<div class="jumbotron" style="background-image: linear-gradient(to right, #00a8ff, #4cd137);">
    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-center">
                <h1 style="font-family: 'Permanent Marker', cursive; font-size: 50px; color: white;">
                    Welcome to the Face MaskDetector Online
                </h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <img src="/static/images/stay-safe.jpg" class="img-thumbnail img-fluid mx-auto d-block">
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-6 d-flex justify-content-end">
                <button id="start" onclick="start()" class="btn btn-success"><i class="fa fa-video-camera"
                        aria-hidden="true"></i> Start
                </button>
            </div>
            <div class="col-6 d-flex justify-content-start">
                <button id="stop" onclick="stop()" class="btn btn-danger active"><i class="fa fa-stop"
                        aria-hidden="true"></i> Stop
                </button>
            </div>
        </div>
        <hr>
        <div class="row" style="color: white;">
            <h4>What is this?</h4>
        </div>
        <div class="row" style="color: white;">
            <p>This is a mask detector, an algorithm based on deep neural networks that detects people through your
                camera and write a bounding box around faces,
                looking if they were masks or not.</p>
        </div>
        <div class="row mb-5">
            <h4 class="d-flex mx-auto lead" style="color: #c23616; font-size: 25px; font-weight: bold;">
                <strong>Stay safe and wear mask.
                    Maintain Social
                    distancing</strong>.</p>
                <h4></h4>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
    $(document).ready(function () {
        $('#image-detector').attr('class', 'nav-item');
        $('#live').attr('class', 'nav-item active');
    })

    function stop() {
        $("img").attr("src", "/static/images/stay-safe.jpg");
        $("#stop").attr("class", "btn btn-danger active");

        $("#start").attr("class", "btn btn-success");
    }
    function start() {
        $("img").attr("src", "{{url_for('main.video_feed')}}");
        $("#start").attr("class", "btn btn-success active");

        $("#stop").attr("class", "btn btn-danger");
    }

</script>

{% endblock %}

app/templates/image_detector.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-12">
            <h1>Try the mask detector on custom images</h1>
        </div>
    </div>
</div>
<div class="container">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <img src="/static/images/mask.jpg" id="image-preview" style="max-width:600px"
                    class="img-thumbnail img-fluid mx-auto d-block">
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-12 d-flex justify-content-center">

                <form enctype="multipart/form-data" id="image-form" method="POST">
                    <div class="row" id="form-row">
                        <div class="col-12">
                            {{ form.csrf_token() }}

                            {{ form.image.label(class="custom-file-label") }}
                            {% if form.image.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.image.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <div class="custom-file">
                                {{ form.image(class="custom-file-input",
                                id="new-image", onchange="previewImage(event)") }}
                            </div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="row mt-3">
                        <div class="col-12 d-flex justify-content-center">
                            {{ form.submit(class="btn btn-primary", id ="submit", disabled=True)}}
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <hr>
        <div class="row" style="color: white;">
            <h4>What is this?</h4>
        </div>
        <div class="row" style="color: white;">
            <p>This is a mask detector, an algorithm based on deep neural networks that detects people through your
                camera and write a bounding box around faces,
                looking if they were masks or not.</p>
        </div>
        <div class="row mb-5">
            <h4 class="d-flex mx-auto lead" style="color: #c23616; font-size: 25px; font-weight: bold;">
                <strong>Stay safe and wear mask.
                    Maintain Social
                    distancing</strong>.</p>
                <h4></h4>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
    var previewImage = function (event) {
        var element_id = "image-preview";
        var preview = document.getElementById(element_id);
        preview.src = URL.createObjectURL(event.target.files[0]);
        preview.style.display = "block";
        $("#submit").prop("disabled", false);
    };
    $(document).ready(function () {
        $('#live').attr('class', 'nav-item');
        $('#image-detector').attr('class', 'nav-item active');
    })
    $(function () {
        $("#submit").each(function (index) {
            $(this).on('click', function (e) {

                var url = "{{ url_for('main.image_processing') }}";

                // Form data
                var formData = new FormData();

                // Add form data
                $('#image-form').serializeArray().forEach(
                    function (item, index) {
                        formData.append(item.name, item.value);
                    }
                );
                // Add the files
                var image = $('#new-image')[0].files[0];
                formData.append('image', image);

                // AJAX query to the endpoint for deletion
                $.ajax({
                    type: "POST", // POST HTTP
                    url: url + '',
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (response) {

                        $("#image-preview").attr("src", response);
                        $("#submit").replaceWith('<button class="btn btn-success"><i class="fa fa-check-circle" onclick="location.reload()" aria-hidden="true"></i> Done!</button>');
                        $("#form-row").remove();
                    },
                    error: function (response) {
                        location.reload();
                        // Redirect to this page
                    }
                });

                return false;
            })
        })
    })
</script>

{% endblock %}

app/templates/login.html
{% extends "template.html" %}


{% block content %}
<div class="container">
    <div class="login">
        <h1>Login</h1>
        <div class="links">
            <a href="/login" class="active">Login</a>
            <a href="/register">Register</a>
        </div>
        <form action="/login" method="post">
            <label for="username">
                <i class="fas fa-user"></i>
            </label>
            <input type="text" name="username" placeholder="Username" id="username" required>
            <label for="code">
                <i class="fa fa-id-card"></i>
            </label>
            <input type="text" name="code" placeholder="Employee Code" id="code" required>
            <label for="password">
                <i class="fas fa-lock"></i>
            </label>
            <input type="password" name="password" placeholder="Password" id="password" required>
            <div class="msg" style="color: red;">{{ msg }}</div>
            <input type="submit" value="Login">
        </form>
    </div>
</div>
{% endblock content %}

app/templates/register.html
{% extends "template.html" %}


{% block content %}
<div class="container">
    <div class="register">
        <h1>Register</h1>
        <div class="links">
            <a href="/login">Login</a>
            <a href="/register" class="active">Register</a>
        </div>
        <form action="/register" method="post" autocomplete="off">
            <label for="name">
                <i class="fa fa-user-circle"></i>
            </label>
            <input type="text" name="name" placeholder="Name" id="name" required>
            <label for="username">
                <i class="fas fa-user"></i>
            </label>
            <input type="text" name="username" placeholder="Username" id="username" required>
            <label for="code">
                <i class="fa fa-id-card"></i>
            </label>
            <input type="text" name="code" placeholder="Employee Code" id="code" required>
            <label for="password">
                <i class="fas fa-lock"></i>
            </label>
            <input type="password" name="password" placeholder="Password" id="password" required>
            <label for="email">
                <i class="fas fa-envelope"></i>
            </label>
            <input type="email" name="email" placeholder="Email" id="email" required>
            <div class="msg" style="color: rgb(8, 218, 8);">{{ msg }}</div>
            <input type="submit" value="Register">
        </form>
    </div>
</div>
{% endblock content %}

app/templates/template.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">

    <title>Real Time Face Mask Detector </title>
    <style>
        body {
            background-image: linear-gradient(to right, #00a8ff, #4cd137);
        }

        .footer-link {
            color: inherit;
        }

        .footer-link:hover {
            color: inherit;
        }

        body {
            margin: 0;
        }

        .wrapper {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        .footer {
            margin-top: auto;
        }

        .login,
        .register {
            width: 400px;
            background-color: #ffffff;
            box-shadow: 0 0 9px 0 rgba(0, 0, 0, 0.3);
            margin: 100px auto;
        }

        .login h1,
        .register h1 {
            text-align: center;
            color: #5b6574;
            font-size: 24px;
            padding: 20px 0 20px 0;
            border-bottom: 1px solid #dee0e4;
        }

        .login .links,
        .register .links {
            display: flex;
            padding: 0 15px;
        }

        .login .links a,
        .register .links a {
            color: #adb2ba;
            text-decoration: none;
            display: inline-flex;
            padding: 0 10px 10px 10px;
            font-weight: bold;
        }

        .login .links a:hover,
        .register .links a:hover {
            color: #9da3ac;
        }

        .login .links a.active,
        .register .links a.active {
            border-bottom: 3px solid #3274d6;
            color: #3274d6;
        }

        .login form,
        .register form {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            padding-top: 20px;
        }

        .login form label,
        .register form label {
            display: flex;
            justify-content: center;
            align-items: center;
            width: 50px;
            height: 50px;
            background-color: #3274d6;
            color: #ffffff;
        }

        .login form input[type="password"],
        .login form input[type="text"],
        .login form input[type="email"],
        .register form input[type="password"],
        .register form input[type="text"],
        .register form input[type="email"] {
            width: 310px;
            height: 50px;
            border: 1px solid #dee0e4;
            margin-bottom: 20px;
            padding: 0 15px;
        }

        .login form input[type="submit"],
        .register form input[type="submit"] {
            width: 100%;
            padding: 15px;
            margin-top: 20px;
            background-color: #3274d6;
            border: 0;
            cursor: pointer;
            font-weight: bold;
            color: #ffffff;
            transition: background-color 0.2s;
        }

        .login form input[type="submit"]:hover,
        .register form input[type="submit"]:hover {
            background-color: #2868c7;
            transition: background-color 0.2s;
        }

        /* Scrollbar Styling */
        ::-webkit-scrollbar {
            width: 10px;
        }

        ::-webkit-scrollbar-track {
            background-color: #ebebeb;
            -webkit-border-radius: 10px;
            border-radius: 10px;
        }

        ::-webkit-scrollbar-thumb {
            -webkit-border-radius: 10px;
            border-radius: 10px;
            background: #07a8e7;
        }
    </style>
</head>

<body>
    <div class="wrapper">
        <div class="header">

            <!--navbar start-->
            <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
                <a class="navbar-brand" href="">Face Mask Detector</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active" id="live">
                            <a class="nav-link" href="/">Live detector</a>
                        </li>
                        <!-- <li class="nav-item" id="image-detector">
                            <a class="nav-link" href="/image-mask-detector">Image mask detector</a>
                        </li> -->
                    </ul>
                    <div class="navbar-nav">
                        <a class="nav-item nav-link" href="/login">Login</a>
                        <a class="nav-item nav-link" href="/register">Register</a>
                    </div>
                </div>
            </nav>
            <!--navbar end-->
        </div>
        <div class="content">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            {{ message }}
            {% endfor %}
            {% endif %}
            {% endwith %}

            <!--add custom content with inheritance-->
            {% block content %}
            {% endblock %}
        </div>
        <div class="footer">
            <div class="py-4 bg-dark text-white-50">
                <div class="container">
                    <div class="row">
                        <div class="col-12 text-center">
                            <p>Follow Us here:</p>
                            <div class="row">
                                <div class="col-4">
                                    <a><i class="fa fa-github my-auto mx-2" aria-hidden="true"></i><strong>Abhijit
                                            Pal</strong></a>
                                    <br>
                                    <a><i class="fa fa-github my-auto mx-2" aria-hidden="true"></i><strong>Ahemed
                                            Atik</strong></a>
                                </div>
                                <div class="col-4">
                                    <a><i class="fa fa-github my-auto mx-2" aria-hidden="true"></i><strong>Amlan
                                            Dutta</strong></a>
                                    <br>
                                    <a><i class="fa fa-github my-auto mx-2" aria-hidden="true"></i><strong>Amisha
                                            Kumari</strong></a>
                                </div>
                                <div class="col-4">
                                    <a><i class="fa fa-github my-auto mx-2" aria-hidden="true"></i><strong>MD Akram
                                            Khan</strong></a>
                                    <br>
                                    <a><i class="fa fa-github my-auto mx-2" aria-hidden="true"></i><strong>Mriganka
                                            Bhadra</strong></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery, Popper.js, and Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
    {% block custom_js %}
    {% endblock %}
</body>

</html>